In [234]:
# On importe les librairies dont on aura besoin pour ce tp
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats



# On charge le dataset
df_init = pd.read_csv("../csv/clean.csv", sep=',')

In [235]:
df.fillna("0")
df_obj = df_init.select_dtypes(include=['object'])
df_obj['SalePrice'] = df_init.loc[:,['SalePrice']]

<ipython-input-235-03bd932f8e82>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_obj['SalePrice'] = df_init.loc[:,['SalePrice']]

d'aprés l'ananlyse des variables quantitaives faite precedemment il y a 5 variables non pertinentes: 
    Si une variable à la même valeur dans tous le jeu de donnée elle n'a aucun intéret:
- street (99.59% en pavé)
- Utilities (99.93% AllPub)
- Condition2 (98.97% Norm)
- RoofMatl (98.22% CompShg)
- Heating (97.81% en GasA)

In [236]:
df_train =df_obj.drop(columns=['Street','Condition2', 'RoofMatl','Heating','Utilities'])
df_train.columns

Index(['MSZoning', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'BldgType', 'HouseStyle', 'RoofStyle',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
       'PavedDrive', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

# with one columns

## Label encoding

In [237]:
from sklearn.preprocessing import LabelEncoder

# creating instance of labelencoder
labelencoder = LabelEncoder()

# Assigning numerical values and storing in another column
df_train['HouseStyle_cat'] = labelencoder.fit_transform(df_train['HouseStyle'])
df_train

,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,...,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition,SalePrice,HouseStyle_cat
0,RL,Reg,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,208500,5
1,RL,Reg,Lvl,FR2,Gtl,Veenker,Feedr,1Fam,1Story,Gable,...,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,181500,2
2,RL,IR1,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,223500,5
3,RL,IR1,Lvl,Corner,Gtl,Crawfor,Norm,1Fam,2Story,Gable,...,Typ,Detchd,Unf,TA,TA,Y,WD,Abnorml,140000,5
4,RL,IR1,Lvl,FR2,Gtl,NoRidge,Norm,1Fam,2Story,Gable,...,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,250000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Reg,Lvl,Inside,Gtl,Gilbert,Norm,1Fam,2Story,Gable,...,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,175000,5
1456,RL,Reg,Lvl,Inside,Gtl,NWAmes,Norm,1Fam,1Story,Gable,...,Min1,Attchd,Unf,TA,TA,Y,WD,Normal,210000,2
1457,RL,Reg,Lvl,Inside,Gtl,Crawfor,Norm,1Fam,2Story,Gable,...,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,266500,5
1458,RL,Reg,Lvl,Inside,Gtl,NAmes,Norm,1Fam,1Story,Hip,...,Typ,Attchd,Unf,TA,TA,Y,WD,Normal,142125,2
1459,RL,Reg,Lvl,Inside,Gtl,Edwards,Norm,1Fam,1Story,Gable,...,Typ,Attchd,Fin,TA,TA,Y,WD,Normal,147500,2

## one hot encoding

In [238]:
from sklearn.preprocessing import OneHotEncoder

In [239]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(df_train[['HouseStyle_cat']]).toarray())

# merge with main df bridge_df on key values
df_train = df_train.join(enc_df)
df_train

,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,...,SalePrice,HouseStyle_cat,0,1,2,3,4,5,6,7
0,RL,Reg,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,208500,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,RL,Reg,Lvl,FR2,Gtl,Veenker,Feedr,1Fam,1Story,Gable,...,181500,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,RL,IR1,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,223500,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,RL,IR1,Lvl,Corner,Gtl,Crawfor,Norm,1Fam,2Story,Gable,...,140000,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,RL,IR1,Lvl,FR2,Gtl,NoRidge,Norm,1Fam,2Story,Gable,...,250000,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Reg,Lvl,Inside,Gtl,Gilbert,Norm,1Fam,2Story,Gable,...,175000,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1456,RL,Reg,Lvl,Inside,Gtl,NWAmes,Norm,1Fam,1Story,Gable,...,210000,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1457,RL,Reg,Lvl,Inside,Gtl,Crawfor,Norm,1Fam,2Story,Gable,...,266500,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1458,RL,Reg,Lvl,Inside,Gtl,NAmes,Norm,1Fam,1Story,Hip,...,142125,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1459,RL,Reg,Lvl,Inside,Gtl,Edwards,Norm,1Fam,1Story,Gable,...,147500,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

# with many columns

In [240]:
df = df_train.copy()
df = df.replace(np.nan, '', regex=True)
df.head(3)

,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,...,SalePrice,HouseStyle_cat,0,1,2,3,4,5,6,7
0,RL,Reg,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,208500,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,RL,Reg,Lvl,FR2,Gtl,Veenker,Feedr,1Fam,1Story,Gable,...,181500,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,RL,IR1,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,223500,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [241]:
df = df.select_dtypes(include=[object])
df.head(3)

,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,...,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,RL,Reg,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1,RL,Reg,Lvl,FR2,Gtl,Veenker,Feedr,1Fam,1Story,Gable,...,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
2,RL,IR1,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal

In [242]:
df.shape

(1460, 33)

In [243]:
# import preprocessing from sklearn
from sklearn import preprocessing

# view columns using df.columns
df.columns

Index(['MSZoning', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'BldgType', 'HouseStyle', 'RoofStyle',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
       'PavedDrive', 'SaleType', 'SaleCondition'],
      dtype='object')

## Label Encoder

In [244]:
# TODO: create a LabelEncoder object and fit it to each feature in ohe

# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()

# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
df_2 = df.apply(le.fit_transform)
df_2.head()

,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,...,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,3,3,3,4,0,5,2,0,5,1,...,5,2,6,2,2,5,5,2,8,4
1,3,3,3,2,0,24,1,0,2,1,...,5,3,6,2,2,5,5,2,8,4
2,3,0,3,4,0,5,2,0,5,1,...,5,2,6,2,2,5,5,2,8,4
3,3,0,3,0,0,6,2,0,5,1,...,5,2,6,6,3,5,5,2,8,0
4,3,0,3,2,0,15,2,0,5,1,...,5,2,6,2,2,5,5,2,8,4

### regression lineaire multiple

In [245]:
y = df_init.SalePrice
X = df_2

In [246]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, y, train_size=0.8)

In [247]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(xtrain, ytrain)

LinearRegression()

In [248]:
print("Le coefficient β1 est égal à {} tandis que l'intercept β0 est égal à {}"
      .format(round(regr.coef_[0],2),round(regr.intercept_)))

Le coefficient β1 est égal à 1406.74 tandis que l'intercept β0 est égal à 214611

In [249]:
from sklearn.metrics import mean_squared_error, r2_score

In [250]:
ytrainpred = regr.predict(xtrain)
ytestpred = regr.predict(xtest)

print ("Pour les données d'entrainement le R2 vaut {} alors que pour les données de test, il est de {}" 
      .format(round(r2_score(ytrain, ytrainpred),3), round(r2_score(ytest, ytestpred),3)))

Pour les données d'entrainement le R2 vaut 0.64 alors que pour les données de test, il est de 0.651

In [251]:
print ("Pour les données d'entrainement le RMSE vaut {} alors que pour les données de test, il est de {}" 
      .format(round(mean_squared_error(ytrain, ytrainpred, squared=False),3), 
              round(mean_squared_error(ytest, ytestpred, squared=False),3)))

Pour les données d'entrainement le RMSE vaut 47637.683 alors que pour les données de test, il est de 46888.811

## One hot encoding

In [204]:
# TODO: create a OneHotEncoder object, and fit it to all of X

# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(df)

# 3. Transform
onehotlabels = enc.transform(df).toarray()
onehotlabels.shape

# as you can see, you've the same number of rows 891
# but now you've so many more columns due to how we changed all the categorical data into numerical data

onehotlabels

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

### regression lineaire multiple

In [253]:
y = df_init.SalePrice
X = onehotlabels

In [254]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, y, train_size=0.8)

In [255]:
from sklearn import linear_model
regr = linear_model.Lasso(alpha=1000)
regr.fit(xtrain, ytrain)

Lasso(alpha=1000)

In [256]:
print("Le coefficient β1 est égal à {} tandis que l'intercept β0 est égal à {}"
      .format(round(regr.coef_[0],2),round(regr.intercept_)))

Le coefficient β1 est égal à -0.0 tandis que l'intercept β0 est égal à 166059

In [257]:
from sklearn.metrics import mean_squared_error, r2_score

In [258]:
ytrainpred = regr.predict(xtrain)
ytestpred = regr.predict(xtest)

print ("Pour les données d'entrainement le R2 vaut {} alors que pour les données de test, il est de {}" 
      .format(round(r2_score(ytrain, ytrainpred),3), round(r2_score(ytest, ytestpred),3)))

Pour les données d'entrainement le R2 vaut 0.729 alors que pour les données de test, il est de 0.695

In [259]:
print ("Pour les données d'entrainement le RMSE vaut {} alors que pour les données de test, il est de {}" 
      .format(round(mean_squared_error(ytrain, ytrainpred, squared=False),3), 
              round(mean_squared_error(ytest, ytestpred, squared=False),3)))

Pour les données d'entrainement le RMSE vaut 40730.762 alors que pour les données de test, il est de 46233.389